export const actionType = {
  SET_SEARCH: "SET_SEARCH",
  SET_SUFFIX: "SET_SUFFIX",
  SET_SUFFIXLIST: "SET_SUFFIXLIST",
  SET_DOMAINDATA: "SET_DOMAINDATA",
  SET_DISPLAYDOMAINDATA: "SET_DISPLAYDOMAINDATA",
  SET_LAYOUT: "SET_LAYOUT",
  SET_AVAILABLE: "SET_AVAILABLE",
};
